### ISSUE TITLE
Merge conflicts met werken in de zelfde branch

### ISSUE THREAD

**Issue by DinandRengers** [DinandRengers/SunnySocks-P1-IC-INF-1D#14]
We moeten even bespreken hoe we dit beter kunnen doen bij het volgende altelier.

**Comment by DinandRengers** [comment]
Maandag 14 oktober, bij het volgende altelier.

**Comment by PascalWesterhof** [comment]
eerst kijken in welke branch jij zit: git branch -a
daarna verplaatsen naar branch: git switch *branch*

**Comment by DinandRengers** [comment]
git checkout -b Blogs origin/Blogs

Met deze command kan je in een aparte branch terwijl het de remote branch tracked.
