### ISSUE TITLE
PHP functies

### ISSUE THREAD

**Issue by PascalWesterhof** [DinandRengers/SunnySocks-P1-IC-INF-1D#17]
Dynamische kleuren populaire blogs - Pascal
Winkelmand pagina dynamisch maken - Dinand
Producten wisselen op homepagina per refresh - Julian
Zoeken op website - Robbin
Contact formulier - Silvio

misschien andere functies nog verzinnen?

**Comment by PascalWesterhof** [comment]
@DinandRengers is het een idee om dit te bespreken met frans voordat wij de php functies maken?

**Comment by DinandRengers** [comment]
Toevoegen aan winkelwand moet een database achter en is ook javascript nodig, dus die kunnen we niet doen. Verander die maar naar "Prijs voor aantal producten".
